AWSTemplateFormatVersion: "2010-09-09"
Description: OU CI/CD pipeline

Parameters:
  GithubBranch:
    AllowedPattern: ".+"
    Type: String
    Description: "Github branch name e.g. development"
    Default: "main"

  GithubOwner:
    AllowedPattern: ".+"
    Type: String
    Description: "Github repo owner"

  ResourceNamePrefix:
    Description: Please specify the application name prefix for all the resources
    Type: String
    Default: ""

  TemplateBucket:
    Type: String
    Default: ""

  # CodeBuildProjectRoleARN:
  #   Description: Please specify the Code Build Project Role ARN
  #   Type: String
  #   Default: ""
  
  # CodePipelineRoleARN:
  #   Description: Please specify the Code Pipeline Role ARN
  #   Type: String
  #   Default: ""

  # CloudWatchEventRoleARN:
  #   Description: CloudWatch Event Role ARN for Code Pipeline
  #   Type: String
  #   Default: ""

  AppRepositoryName:
    Description: Name of the Github Repository
    Type: String
    Default: ""

  AppRepositoryDescription:
    Description: Description of the Github Repository
    Type: String
    Default: ""

  # TESTApprovalSNSARN:
  #   Type: String
  #   Description: TEST SNS Notification ARN
  #   Default: ""

  # ProdApprovalSNSARN:
  #   Type: String
  #   Description: Prod SNS Notification ARN
  #   Default: ""

Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Retain
    Properties:
      BucketName: !Ref TemplateBucket

  OUCICDCodeDevBuildProject:
    Type: AWS::CodeBuild::Project
    DependsOn: S3Bucket
    Properties:
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        EnvironmentVariables:
          - Name: DEPLOY_ENV
            Type: PLAINTEXT
            Value: dev
          - Name: AWS_REGION
            Value:
              Ref: AWS::Region
          - Name: ARTIFACTS_BUCKET
            Value:
              Ref: TemplateBucket
          - Name: REPOSITORY_NAME
            Value:
              Ref: AppRepositoryName
        Image: aws/codebuild/standard:5.0
        ImagePullCredentialsType: CODEBUILD
        PrivilegedMode: true
        Type: LINUX_CONTAINER
      ServiceRole: !ImportValue CodePipelineBuildProjectRoleOutput
      Source:
        Type: CODEPIPELINE
      EncryptionKey: alias/aws/s3
      TimeoutInMinutes: 240
      Name: !Sub '${ResourceNamePrefix}-dev-deploy-codebuild-project'

  OUCICDCodeTESTBuildProject:
    Type: AWS::CodeBuild::Project
    DependsOn: S3Bucket
    Properties:
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        EnvironmentVariables:
          - Name: DEPLOY_ENV
            Type: PLAINTEXT
            Value: test
          - Name: AWS_REGION
            Value:
              Ref: AWS::Region
          - Name: ARTIFACTS_BUCKET
            Value:
              Ref: TemplateBucket
          - Name: REPOSITORY_NAME
            Value:
              Ref: AppRepositoryName
        Image: aws/codebuild/standard:5.0
        ImagePullCredentialsType: CODEBUILD
        PrivilegedMode: true
        Type: LINUX_CONTAINER
      ServiceRole: !ImportValue CodePipelineBuildProjectRoleOutput
      Source:
        Type: CODEPIPELINE
      EncryptionKey: alias/aws/s3
      TimeoutInMinutes: 240
      Name: !Sub '${ResourceNamePrefix}-test-deploy-codebuild-project'

  OUCICDCodeProdBuildProject:
    Type: AWS::CodeBuild::Project
    DependsOn: S3Bucket
    Properties:
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        EnvironmentVariables:
          - Name: DEPLOY_ENV
            Type: PLAINTEXT
            Value: prod
          - Name: AWS_REGION
            Value:
              Ref: AWS::Region
          - Name: ARTIFACTS_BUCKET
            Value:
              Ref: TemplateBucket
          - Name: REPOSITORY_NAME
            Value:
              Ref: AppRepositoryName
        Image: aws/codebuild/standard:5.0
        ImagePullCredentialsType: CODEBUILD
        PrivilegedMode: true
        Type: LINUX_CONTAINER
      ServiceRole: !ImportValue CodePipelineBuildProjectRoleOutput
      Source:
        Type: CODEPIPELINE
      EncryptionKey: alias/aws/s3
      TimeoutInMinutes: 240
      Name: !Sub '${ResourceNamePrefix}-prod-deploy-codebuild-project'

  OUCICDTemplateScanner:
    Type: AWS::CodeBuild::Project
    DependsOn: S3Bucket
    Properties:
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        EnvironmentVariables:
          - Name: DEPLOY_ENV
            Type: PLAINTEXT
            Value: prod
          - Name: AWS_REGION
            Value:
              Ref: AWS::Region
          - Name: ARTIFACTS_BUCKET
            Value:
              Ref: TemplateBucket
          - Name: REPOSITORY_NAME
            Value:
              Ref: AppRepositoryName
        Image: aws/codebuild/standard:5.0
        ImagePullCredentialsType: CODEBUILD
        PrivilegedMode: true
        Type: LINUX_CONTAINER
      ServiceRole: !ImportValue CodePipelineBuildProjectRoleOutput
      Source:
        Type: CODEPIPELINE
        BuildSpec: !Sub |
          version: 0.2
          phases:
            install:
              commands:
                - ls
                - gem install cfn-nag
            pre_build:
              commands:
                - cfn_nag_scan --input-path templates/
                - for tmplt in $(ls ./template); 
                  do
                      rel_url=$ARTIFACTS_BUCKET/templates/${ResourceNamePrefix}/$tmplt;
                      aws s3 cp ./templates/$tmplt s3://$rel_url --acl bucket-owner-full-control;
                      aws cloudformation validate-template --template-url https://s3.amazonaws.com/$rel_url;
                  done
      EncryptionKey: alias/aws/s3
      Name: !Sub '${ResourceNamePrefix}-cfn-scanner-codebuild-project'
  OUCICDPipeline:
    Type: AWS::CodePipeline::Pipeline
    DependsOn: S3Bucket
    Properties:
      RoleArn: !ImportValue CodePipelineRoleOutput
      Name: !Sub '${ResourceNamePrefix}-cicd-pipeline'
      PipelineType: "V2" 
      Triggers:
        - GitConfiguration: 
            SourceActionName: "Source-Action"
            Push:
              - Branches:
                  Includes: 
                    - "main"
          ProviderType: "CodeStarSourceConnection"
      Stages:
        - Actions:
            - ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeStarSourceConnection
                Version: "1"
              Configuration:
                ConnectionArn: !ImportValue GithubConnection
                FullRepositoryId: !Sub "${GithubOwner}/${AppRepositoryName}"
                BranchName: !Ref GithubBranch
              Name: Source-Action
              OutputArtifacts:
                - Name: SourceArtifact
              RunOrder: 1
          Name: Source
        - Actions:
            - ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: "1"
              Configuration:
                ProjectName: !Ref OUCICDTemplateScanner
              InputArtifacts:
                - Name: SourceArtifact
              Name: Build-Action
              OutputArtifacts:
                - Name: ScannedArtifact
              RunOrder: 1
          Name: CFN-Scanner
        - Actions:
            - ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: "1"
              Configuration:
                ProjectName: !Ref OUCICDCodeDevBuildProject
              InputArtifacts:
                - Name: SourceArtifact
              Name: Build-Action
              OutputArtifacts:
                - Name: DevBuildArtifact
              RunOrder: 1
          Name: Dev-Deployment
        - Actions:
            - ActionTypeId:
                Category: Approval
                Owner: AWS
                Provider: Manual
                Version: "1"
              Configuration:
                NotificationArn: 
                  !ImportValue TESTApprovalTopicArn
              Name: Pipeline-Approval
              RunOrder: 1
          Name: Procceed-to-TEST-Approval
        - Actions:
            - ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: "1"
              Configuration:
                ProjectName: !Ref OUCICDCodeDevBuildProject
                EnvironmentVariables: 
                  - Name: "TRANSITION_ACTION"
                    Type: "PLAINTEXT"
                    Value: "True"
              InputArtifacts:
                - Name: SourceArtifact
              Name: Build-Action
              OutputArtifacts:
                - Name: DevBuildArtifact
              RunOrder: 1
          Name: Dev-Transition-Action
        - Actions:
            - ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: "1"
              Configuration:
                ProjectName: !Ref OUCICDCodeTESTBuildProject                
              InputArtifacts:
                - Name: SourceArtifact
              Name: Build-Action
              OutputArtifacts:
                - Name: TESTBuildArtifact
              RunOrder: 1
          Name: TEST-Deployment
        - Actions:
            - ActionTypeId:
                Category: Approval
                Owner: AWS
                Provider: Manual
                Version: "1"
              Configuration:
                NotificationArn: 
                  !ImportValue ProdApprovalTopicArn
              Name: Pipeline-Approval
              RunOrder: 1
          Name: Procceed-to-Prod-Approval
        - Actions:
            - ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: "1"
              Configuration:
                ProjectName: !Ref OUCICDCodeProdBuildProject
              InputArtifacts:
                - Name: SourceArtifact
              Name: Build-Action
              OutputArtifacts:
                - Name: ProdBuildArtifact
              RunOrder: 1
          Name: Prod-Deployment
      ArtifactStore:
        Location:
          Ref: TemplateBucket
        Type: S3

Outputs:
  CICDPipelineName:
    Value: !Ref OUCICDPipeline
    Description: CICD Pipeline Name