AWSTemplateFormatVersion: "2010-09-09"
Description: OU CI/CD pipeline (SNS Topics)

Parameters:
  ResourceNamePrefix:
    Description: Please specify the prefix for all the resources
    Type: String
    Default: ""

  PRApprovalSNSEmail:
    Type: String
    Description: Email address to which Prod approval should be sent
    AllowedPattern: "([a-zA-Z0-9_\\-\\.]+)@((\\[[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.)|(([a-zA-Z0-9\\-]+\\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\\]?)"
    ConstraintDescription: Must be a valid email address. (e.g. name@example.com)  

  TESTApprovalSNSEmail:
    Type: String
    Description: Email address to which Prod approval should be sent
    AllowedPattern: "([a-zA-Z0-9_\\-\\.]+)@((\\[[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.)|(([a-zA-Z0-9\\-]+\\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\\]?)"
    ConstraintDescription: Must be a valid email address. (e.g. name@example.com)  

  ProdApprovalSNSEmail:
    Type: String
    Description: Email address to which Prod approval should be sent
    AllowedPattern: "([a-zA-Z0-9_\\-\\.]+)@((\\[[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.)|(([a-zA-Z0-9\\-]+\\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\\]?)"
    ConstraintDescription: Must be a valid email address. (e.g. name@example.com)  

Resources:

  OUCICDPipelinePRApprovalTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub "${ResourceNamePrefix}-pull-request-approval-topic"
      DisplayName: !Sub "${ResourceNamePrefix}-pull-request-approval"
      Subscription:
        - 
          Endpoint:
            Ref: PRApprovalSNSEmail
          Protocol: "email"

  OUCICDPipelineTESTApprovalTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub "${ResourceNamePrefix}-test-approval-topic"
      DisplayName: !Sub "${ResourceNamePrefix}-test-approval"
      Subscription:
        - 
          Endpoint:
            Ref: TESTApprovalSNSEmail
          Protocol: "email"

  OUCICDPipelineProdApprovalTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub "${ResourceNamePrefix}-prod-approval-topic"
      DisplayName: !Sub "${ResourceNamePrefix}-prod-approval"
      Subscription:
        - 
          Endpoint:
            Ref: ProdApprovalSNSEmail
          Protocol: "email"


Outputs:
  PRApprovalTopicArn:
    Description: Arn of Created Pull Request SNS Topic
    Value: !Ref OUCICDPipelinePRApprovalTopic
    Export:
      Name: "PRApprovalTopicArn"
  TESTApprovalTopicArn:
    Description: Arn of Created TEST SNS Topic
    Value: !Ref OUCICDPipelineTESTApprovalTopic
    Export:
      Name: "TESTApprovalTopicArn"
  ProdApprovalTopicArn:
    Description: Arn of Created Prod SNS Topic
    Value: !Ref OUCICDPipelineProdApprovalTopic
    Export:
      Name: "ProdApprovalTopicArn"

