version: 0.2

phases:
  install:
    commands:
      - pip3 install boto3

  pre_build:
    commands:
      # Do not change the values of below variables
      - TEMPLATE_FILE_PATH=./templates
      - DEPLOYMENT_SCRIPT_FILE=./deploy_scripts/deploy.py
      - CICD_BUCKET=ou-cicd-pipeline-artifact
      - CICD_BUCKET_PREFIX=ou-cicd-pipeline-app-prereqs
      - |
        if [ -z ${TRANSITION_TYPE+x} ]; then 
          echo "TRANSITION_TYPE is unset; defaulting to 'retain'"
          TRANSITION_TYPE="retain"
        fi
  build:
    commands:

      - echo "Triggering deployment.."
      - python $DEPLOYMENT_SCRIPT_FILE --env $DEPLOY_ENV --region $AWS_REGION --s3_bucket $ARTIFACTS_BUCKET --app_name $REPOSITORY_NAME --transition_type $TRANSITION_TYPE;
